## Pod scheduling preferences.
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}

## Set toleration for scheduler
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

service:
    type: ClusterIP

imageCredentials:
    enabled: false
    name: pull-secrets

JWTKeys:
  # These are example keys, please get valid keys for your deployment
  # The name you assign to each variable will be used as the file name. Using the following examples, three key files will be created:
  # - /opt/finance-portal-backend-service/secrets/first_key.key
  # - /opt/finance-portal-backend-service/secrets/second_key.key
  # - /opt/finance-portal-backend-service/secrets/third_key.key
  first_key.key: |-
    -----BEGIN RSA PUBLIC KEY-----
    MIICXQIBAAKBgQCyQ80uaA1DKxjwuGgetuHiXoZxpQ/Twyj/9a5zeMCfZlAvreCs
    8MhCm17OuQkYkiIpoEwn3DUDXAO03kUg9Hg5pd5ObnTZdWoBKWR1t/U2R4xU6v2w
    KLn9KyK/cA/79wzaiMZS+H+j+pt9ZjgdpKOcn3XK8bOURIVEsSNu8+yZ/wIDAQAB
    AoGAULdvj9wwaSH6DIFLL+EaHYA0ev/Ez1tWVLN/NqzN9z8B/tzJ1zS9UJ9+Sbcx
    3azJiDSbVw8X9/nxebOM9JONXbcCMeJX5MqsBzrR89vTHo9ir91u7LDVBEo+bsrS
    ufTQdT1etUOggwWssU4JLoQB7L7QoFhBTndAc6AwmB1t6pECQQDHBe01qgTQwF4H
    zjnpBKPUlYX5Ma+6VDvSG/yFdJeA58TrF3oBBnET9ZTmy4mDLQaO88wsAx0kduaB
    H8tuoCUvAkEA5UyIpG2djRCyCRkENJLn9qpCaSOwaO43D189KqGzW9nHihMNczha
    akAIa3ULp8AoqPFKOFk+v2jGYwPHSatEMQJBAK9vr/wAFSKWj8y9oxqetnPsIh7a
    B5duLRU3Ck/xyKMeqty44xkIPqFjd5BClsME66UTj0S0sfm0vdfQ2Rh5Ho0CQAaz
    PM7pMRBdK4aeh4Ptwv9vLC+cTlxSkaNOWiAzx2TosS70rZDvVZ0DL/vL2MJXGBkP
    q+aHnRDEw/9CrgEWExECQQCT7jFthoPs29A981euHfZ+bXMFEI48PFgw13cmyWnM
    HijF+4E/XtD11WJkIuDCmHal/oRtcbIO/cCk15xbWZkD
    -----END RSA PUBLIC KEY-----
  second_key.key: |-
    -----BEGIN RSA PUBLIC KEY-----
    MIICXQIBAAKBgQCyQ80uaA1DKxjwuGgetuHiXoZxpQ/Twyj/9a5zeMCfZlAvreCs
    8MhCm17OuQkYkiIpoEwn3DUDXAO03kUg9Hg5pd5ObnTZdWoBKWR1t/U2R4xU6v2w
    KLn9KyK/cA/79wzaiMZS+H+j+pt9ZjgdpKOcn3XK8bOURIVEsSNu8+yZ/wIDAQAB
    AoGAULdvj9wwaSH6DIFLL+EaHYA0ev/Ez1tWVLN/NqzN9z8B/tzJ1zS9UJ9+Sbcx
    3azJiDSbVw8X9/nxebOM9JONXbcCMeJX5MqsBzrR89vTHo9ir91u7LDVBEo+bsrS
    ufTQdT1etUOggwWssU4JLoQB7L7QoFhBTndAc6AwmB1t6pECQQDHBe01qgTQwF4H
    zjnpBKPUlYX5Ma+6VDvSG/yFdJeA58TrF3oBBnET9ZTmy4mDLQaO88wsAx0kduaB
    H8tuoCUvAkEA5UyIpG2djRCyCRkENJLn9qpCaSOwaO43D189KqGzW9nHihMNczha
    akAIa3ULp8AoqPFKOFk+v2jGYwPHSatEMQJBAK9vr/wAFSKWj8y9oxqetnPsIh7a
    B5duLRU3Ck/xyKMeqty44xkIPqFjd5BClsME66UTj0S0sfm0vdfQ2Rh5Ho0CQAaz
    PM7pMRBdK4aeh4Ptwv9vLC+cTlxSkaNOWiAzx2TosS70rZDvVZ0DL/vL2MJXGBkP
    q+aHnRDEw/9CrgEWExECQQCT7jFthoPs29A981euHfZ+bXMFEI48PFgw13cmyWnM
    HijF+4E/XtD11WJkIuDCmHal/oRtcbIO/cCk15xbWZkD
    -----END RSA PUBLIC KEY-----
  third_key.key: |-
    -----BEGIN RSA PUBLIC KEY-----
    MIICXQIBAAKBgQCyQ80uaA1DKxjwuGgetuHiXoZxpQ/Twyj/9a5zeMCfZlAvreCs
    8MhCm17OuQkYkiIpoEwn3DUDXAO03kUg9Hg5pd5ObnTZdWoBKWR1t/U2R4xU6v2w
    KLn9KyK/cA/79wzaiMZS+H+j+pt9ZjgdpKOcn3XK8bOURIVEsSNu8+yZ/wIDAQAB
    AoGAULdvj9wwaSH6DIFLL+EaHYA0ev/Ez1tWVLN/NqzN9z8B/tzJ1zS9UJ9+Sbcx
    3azJiDSbVw8X9/nxebOM9JONXbcCMeJX5MqsBzrR89vTHo9ir91u7LDVBEo+bsrS
    ufTQdT1etUOggwWssU4JLoQB7L7QoFhBTndAc6AwmB1t6pECQQDHBe01qgTQwF4H
    zjnpBKPUlYX5Ma+6VDvSG/yFdJeA58TrF3oBBnET9ZTmy4mDLQaO88wsAx0kduaB
    H8tuoCUvAkEA5UyIpG2djRCyCRkENJLn9qpCaSOwaO43D189KqGzW9nHihMNczha
    akAIa3ULp8AoqPFKOFk+v2jGYwPHSatEMQJBAK9vr/wAFSKWj8y9oxqetnPsIh7a
    B5duLRU3Ck/xyKMeqty44xkIPqFjd5BClsME66UTj0S0sfm0vdfQ2Rh5Ho0CQAaz
    PM7pMRBdK4aeh4Ptwv9vLC+cTlxSkaNOWiAzx2TosS70rZDvVZ0DL/vL2MJXGBkP
    q+aHnRDEw/9CrgEWExECQQCT7jFthoPs29A981euHfZ+bXMFEI48PFgw13cmyWnM
    HijF+4E/XtD11WJkIuDCmHal/oRtcbIO/cCk15xbWZkD
    -----END RSA PUBLIC KEY-----

config:
  azureLogAnalytics:
    authTokenEndpoint: 'https://login.microsoftonline.com'
    clientId: 'ec3b168c-91db-4aa0-a7d3-ea9f6f999999'
    clientSecret: 'secret'
    grantType: 'client_credentials'
    kafkaMessagePattern: "Producer.sendMessage::messageProtocol:'({.*?})'"
    logApiEndpoint: 'https://api.loganalytics.io/v1/'
    redirectUri: 'http://localhost:5000'
    resource: 'https://api.loganalytics.io/'
    searchQueryTemplate:
      regex: "search '(.*)' | where LogEntry matches regex '.*Producer.sendMessage::messageProtocol:.*' | where LogEntry matches regex '.*transferId.*' | where LogEntry matches regex '.*fspiop-signature.*' | take 1 | project LogEntry"
      template: "search '{{transferId}}' | where LogEntry matches regex '.*Producer.sendMessage::messageProtocol:.*' | where LogEntry matches regex '.*transferId.*' | where LogEntry matches regex '.*fspiop-signature.*' | take 1 | project LogEntry"
    tenantId: 'ec3b168c-91db-4aa0-a7d3-ea9f6f999999'
    workspaceId: 'e16d055b-7a9a-4e9b-bb4b-abcdef999999'
  db_host: '$release_name-centralledger-mysql'
  db_port: '3306'
  db_user: 'central_ledger'
  db_password: 'oyMxgZChuu'
  db_database: 'central_ledger'
  fxpEndpoint: '$release_name-fxp-server'
  externalSettlementsEndpoint: '$release_name-external-settlement-server'
  centralSettlementsEndpoint: '$release_name-centralsettlement/v1'
  centralLedgerEndpoint: '$release_name-centralledger-service'
  settlementManagementEndpoint: '$release_name-finance-portal-settlement-management'
  settlementManagementPort: '5000'
  isOauthEnabled: false
  oauthServer: 'https://localhost'
  oauthPort: 9443
  oauthLoginPath: '/oauth2/token'
  oauthTokenValidationPath: '/oauth2/introspect'
  oauthUserInfo: '/oauth2/userinfo'
  oauthTokenRevoke: '/oauth2/revoke'
  oauthClientKey: 'testkey'
  oauthClientSecret: 'testsecret'
  # Do not set to true in production
  corsReflectOrigin: 'false'
  # Do not set to true in production
  BypassAuth: 'true'
  # Do not set to true in production
  InsecureCookie: 'false'
  is_populate:
    name: ispopulate
    http:
      endpoint: 'something'
      timeout: 30000
    authentication:
      type: 'basic'
      credentials:
        username: 'admin'
        password: 'admin'
  jasperUser: 'user'
  jasperPassword: 'password'
  report1: "something"
  report2: "something"

frontend:
  service:
    port: 80
  image:
    repository: mojaloop/finance-portal-ui
    tag: v10.4.0
    pullPolicy: Always
    port: 80
  ingress:
    enabled: true
    externalPath: /(.*)
    hosts:
      api: finance-portal.local
    annotations:
      kubernetes.io/ingress.class: nginx
      ## NGINX Ingres Control < v0.22-
      nginx.ingress.kubernetes.io/rewrite-target: /
      ## NGINX Ingres Control >= v0.22+
      # nginx.ingress.kubernetes.io/rewrite-target: /$1

backend:
  service:
    port: 3000
  image:
    repository: mojaloop/finance-portal-backend-service
    tag: v10.4.0
    pullPolicy: Always
    port: 3000
  init:
    enabled: true
    image:
      repository: mojaloop/finance-portal-backend-service
      tag: v10.4.0
      pullPolicy: Always
  env: 'dev'
  ingress:
    enabled: false
    externalPath: /admin-portal-backend/
    hosts:
      api: finance-portal.local
    annotations:
      kubernetes.io/ingress.class: nginx
      ## NGINX Ingres Control < v0.22-
      nginx.ingress.kubernetes.io/rewrite-target: /
      ## NGINX Ingres Control >= v0.22+
      # nginx.ingress.kubernetes.io/rewrite-target: /$1
