{{- $RELEASE_NAME := .Release.Name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "connection-manager-frontend.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "connection-manager-frontend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  {{- range $k, $v := .Values.config }}
    {{ $k }}: {{ $v | quote | replace "$release_name" $RELEASE_NAME }}
  {{- end }}
