{{- $dbHost := ( .Values.db.host | replace "$release_name" .Release.Name ) -}}

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "finance-portal-settlement-management.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "finance-portal-settlement-management.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app: {{ template "finance-portal-settlement-management.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "finance-portal-settlement-management.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
        {{- if .Values.operatorSettlement.init.enabled }}
        - name: operator-settlement-init
          image: {{ .Values.operatorSettlement.init.image.repository }}
          imagePullPolicy: {{ .Values.operatorSettlement.init.pullPolicy }}
          command:
            - sh
            - "-c"
            - {{ (.Values.operatorSettlement.init.command | replace "$db_user" (print .Values.db.user) | replace "$db_password" (print .Values.db.password) | replace "$db_host" $dbHost | replace "$db_database" (print .Values.db.schema) | replace "$db_port" (print .Values.db.port) )| quote }}
        {{- end }}
        {{- if .Values.settlementManagement.init.enabled }}
        - name: settlement-management-init
          image: {{ .Values.settlementManagement.init.image.repository }}
          imagePullPolicy: {{ .Values.settlementManagement.init.pullPolicy }}
          command:
            - sh
            - "-c"
            - {{ (.Values.settlementManagement.init.command | replace "$db_user" (print .Values.db.user) | replace "$db_password" (print .Values.db.password) | replace "$db_host" $dbHost | replace "$db_database" (print .Values.db.schema) | replace "$db_port" (print .Values.db.port) )| quote }}
        {{- end }}
      containers:
      - name: operator-settlement
        image: "{{ .Values.operatorSettlement.image.repository }}:{{ .Values.operatorSettlement.image.tag }}"
        imagePullPolicy: {{ .Values.operatorSettlement.image.pullPolicy }}
        ports:
        - name: operator
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: operator
        readinessProbe:
          httpGet:
            path: /
            port: operator
        envFrom:
        - configMapRef:
            name: {{ template "finance-portal-settlement-management.fullname" . }}
        - secretRef:
            name: {{ template "finance-portal-settlement-management.fullname" . }}
        resources:
      - name: settlement-management
        image: "{{ .Values.settlementManagement.image.repository }}:{{ .Values.settlementManagement.image.tag }}"
        imagePullPolicy: {{ .Values.settlementManagement.image.pullPolicy }}
        ports:
          - name: management
            containerPort: 5000
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: management
        readinessProbe:
          httpGet:
            path: /
            port: management
        envFrom:
          - configMapRef:
              name: {{ template "finance-portal-settlement-management.fullname" . }}
          - secretRef:
              name: {{ template "finance-portal-settlement-management.fullname" . }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}