{{- if .Values.operatorSettlement.ingress.enabled -}}
{{- $serviceName := include "finance-portal-settlement-management.fullname" . -}}
{{- $operatorSettlementPort := .Values.operatorSettlement.service.port -}}
{{- $operatorSettlementPath := .Values.operatorSettlement.ingress.externalPath -}}
apiVersion: {{ template "finance-portal-settlement-management.apiVersion.Ingress" . }}
kind: Ingress
metadata:
  name: {{ template "finance-portal-settlement-management.fullname" . }}-operator-settlement
  labels:
    app.kubernetes.io/name: {{ include "finance-portal-settlement-management.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    {{- range $key, $value := .Values.operatorSettlement.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.operatorSettlement.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $operatorSettlementPath }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $operatorSettlementPort }}
    {{- end -}}
  {{- if .Values.operatorSettlement.ingress.tls }}
  tls:
    {{ toYaml .Values.operatorSettlement.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
