{{- $centralledgerHost := printf "%s-%s" .Release.Name .Values.centralledger.nameOverride -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "centralhub.fullname" . }}
  labels:
      app:  {{ template "centralhub.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
data:
  default.json: |
    {{ .Values.config.default_json | replace "$service_port" (printf "%.0f" .Values.service.internalPort) | replace "$centralledger_api_port" (printf "%.0f" .Values.centralledger.containers.api.service.ports.api.internalPort) | replace "$centralledger_admin_port" (printf "%.0f" .Values.centralledger.containers.admin.service.ports.api.internalPort) | replace "$ingress_host" (.Values.ingress.hosts | first) | replace "$centralledger_host" $centralledgerHost }}

