{{- $dbHost := ( .Values.config.db_host | replace "$release_name" .Release.Name ) -}}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "finance-portal.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "finance-portal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # Common annotations
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "finance-portal.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "finance-portal.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        # Custom Pod Labels
        {{- if .Values.podLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/config-auth-init: {{ include (print $.Template.BasePath "/configmap-auth-init.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        # Custom Pod annotations
        {{- if .Values.podAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        {{- if .Values.backend.init.enabled }}
        - name: finance-portal-backend-init
          image: {{ .Values.backend.init.image.repository }}
          imagePullPolicy: {{ .Values.backend.init.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.config.is_populate.name }}
            - secretRef:
                name: {{ template "finance-portal.fullname" . }}
        {{- end }}
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - name: backend
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: backend
        readinessProbe:
          httpGet:
            path: /
            port: backend
        envFrom:
        - configMapRef:
            name: {{ template "finance-portal.fullname" . }}
        - secretRef:
            name: {{ template "finance-portal.fullname" . }}
        {{- if .Values.JWTKeys }}
        volumeMounts:
          - name: {{ template "finance-portal.fullname" . }}-secrets-volume
            mountPath: /opt/finance-portal-backend-service/secrets
            readOnly: true
        {{- end }}
        resources:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - name: frontend
          containerPort: {{ .Values.frontend.image.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: frontend
        readinessProbe:
          httpGet:
            path: /
            port: frontend
        envFrom:
        - configMapRef:
            name: {{ template "finance-portal.fullname" . }}
        - secretRef:
            name: {{ template "finance-portal.fullname" . }}
      ## Pod scheduling preferences.
      ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
      affinity: {}

      ## Node labels for pod assignment
      ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
      nodeSelector: {}

      ## Set toleration for scheduler
      ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
      tolerations: []
      {{- if .Values.JWTKeys }}
      volumes:
        - name: {{ template "finance-portal.fullname" . }}-secrets-volume
          secret:
            secretName: {{ template "finance-portal.fullname" . }}-certs
            defaultMode: 511
      {{- end}}
      imagePullSecrets:
      - name: {{ .Values.imageCredentials.name }}
