{{- $dbHost := ( .Values.db.host | replace "$release_name" .Release.Name ) -}}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "finance-portal.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "finance-portal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}001
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "finance-portal.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "finance-portal.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        {{- if .Values.backend.init.enabled }}
        - name: finance-portal-backend-init
          image: {{ .Values.backend.init.image.repository }}
          imagePullPolicy: {{ .Values.backend.init.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.config.is_populate.name }}
            - secretRef:
                name: {{ template "finance-portal.fullname" . }}
        {{- end }}
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - name: backend
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: backend
        readinessProbe:
          httpGet:
            path: /
            port: backend
        envFrom:
        - configMapRef:
            name: {{ template "finance-portal.fullname" . }}
        - secretRef:
            name: {{ template "finance-portal.fullname" . }}
        resources:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - name: frontend
          containerPort: {{ .Values.frontend.image.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: frontend
        readinessProbe:
          httpGet:
            path: /
            port: frontend
        envFrom:
        - configMapRef:
            name: {{ template "finance-portal.fullname" . }}
        - secretRef:
            name: {{ template "finance-portal.fullname" . }}
      imagePullSecrets:
      - name: {{ .Values.imageCredentials.name }}
