apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "centralledger-service.fullname" . }}
  labels:
      app: {{ template "centralledger-service.fullname" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
data:
  server.host: {{ .Values.ingress.hosts.api | quote }}
  server.port: {{ .Values.containers.api.service.ports.api.internalPort | quote }}
  admin.host: {{  .Values.ingress.hosts.admin | quote }}
  admin.port: {{ .Values.containers.admin.service.ports.api.internalPort | quote }}
  default.json: {{ (tpl (.Files.Get .Values.config.default_json) . ) | quote }}
  knexfile.js: {{ (tpl (.Files.Get .Values.config.knexfile_js) . ) | quote }}
