name: mojaloop

sources:
  account-lookup-service:
    kind: helmchart
    spec: 
      url: file://./mojaloop
      name: account-lookup-service
  quoting-service:
    kind: helmchart
    spec: 
      url: file://./mojaloop
      name: quoting-service
  ml-api-adapter:
    kind: helmchart
    spec: 
      url: file://./mojaloop
      name: ml-api-adapter
  centralledger:
    kind: helmchart
    spec: 
      url: file://./mojaloop
      name: centralledger
  centralsettlement:
    kind: helmchart
    spec: 
      url: file://./mojaloop
      name: centralsettlement
  simulator:
    kind: helmchart
    spec: 
      url: file://./mojaloop
      name: simulator
  als-msisdn-oracle:
    kind: helmchart
    spec: 
      url: file://./mojaloop
      name: als-msisdn-oracle
  mojaloop-simulator:
    kind: helmchart
    spec: 
      url: file://./mojaloop
      name: mojaloop-simulator
  mojaloop-bulk:
    kind: helmchart
    spec: 
      url: file://./mojaloop
      name: mojaloop-bulk
  transaction-requests-service:
    kind: helmchart
    spec: 
      url: file://./mojaloop
      name: transaction-requests-service
  thirdparty:
    kind: helmchart
    spec: 
      url: file://./mojaloop
      name: thirdparty
  mojaloop-ttk-simulators:
    kind: helmchart
    spec: 
      url: file://./mojaloop
      name: mojaloop-ttk-simulators
  ml-testing-toolkit:
    kind: helmchart
    spec: 
      url: file://./mojaloop
      name: ml-testing-toolkit
  ml-testing-toolkit-cli:
    kind: helmchart
    spec: 
      url: file://./mojaloop
      name: ml-testing-toolkit-cli
  inter-scheme-proxy-adapter:
    kind: helmchart
    spec: 
      url: file://./mojaloop
      name: inter-scheme-proxy-adapter

  
conditions: {}

targets:
  account-lookup-service:
    sourceid: account-lookup-service
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[0].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  quoting-service:
    sourceid: quoting-service
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[1].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-api-adapter:
    sourceid: ml-api-adapter
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[2].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  centralledger:
    sourceid: centralledger
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[3].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  centralsettlement:
    sourceid: centralsettlement
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[4].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  simulator:
    sourceid: simulator
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[5].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  als-msisdn-oracle:
    sourceid: als-msisdn-oracle
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[6].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  mojaloop-simulator:
    sourceid: mojaloop-simulator
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[7].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  mojaloop-bulk:
    sourceid: mojaloop-bulk
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[8].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  transaction-requests-service:
    sourceid: transaction-requests-service
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[9].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  thirdparty:
    sourceid: thirdparty
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[10].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  mojaloop-ttk-simulators:
    sourceid: mojaloop-ttk-simulators
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[11].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-testing-toolkit:
    sourceid: ml-testing-toolkit
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[13].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-ttk-test-setup:
    sourceid: ml-testing-toolkit-cli
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[14].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-ttk-test-val-gp:
    sourceid: ml-testing-toolkit-cli
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[15].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-ttk-test-val-bulk:
    sourceid: ml-testing-toolkit-cli
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[16].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-ttk-test-setup-tp:
    sourceid: ml-testing-toolkit-cli
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[17].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-ttk-test-val-tp:
    sourceid: ml-testing-toolkit-cli
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[18].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-ttk-posthook-setup:
    sourceid: ml-testing-toolkit-cli
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[19].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-ttk-posthook-tests:
    sourceid: ml-testing-toolkit-cli
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[20].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-ttk-cronjob-tests:
    sourceid: ml-testing-toolkit-cli
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[21].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-ttk-cronjob-cleanup:
    sourceid: ml-testing-toolkit-cli
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[22].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-ttk-test-setup-sdk-bulk:
    sourceid: ml-testing-toolkit-cli
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[23].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-ttk-test-val-sdk-bulk:
    sourceid: ml-testing-toolkit-cli
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[24].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-ttk-test-val-sdk-r2p:
    sourceid: ml-testing-toolkit-cli
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[25].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-ttk-test-setup-interscheme:
    sourceid: ml-testing-toolkit-cli
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[26].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-ttk-test-val-interscheme:
    sourceid: ml-testing-toolkit-cli
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[27].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-ttk-test-cleanup:
    sourceid: ml-testing-toolkit-cli
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[28].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  ml-ttk-test-mcm-rbac:
    sourceid: ml-testing-toolkit-cli
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[29].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
  inter-scheme-proxy-adapter:
    sourceid: inter-scheme-proxy-adapter
    kind: helmchart
    spec:
      name: mojaloop
      file: Chart.yaml
      key: $.dependencies[30].version
    transformers:
      - addprefix: '">= '
      - addsuffix: '"'
