apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "quotingservice.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "quotingservice.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  default.json: {{ (tpl (.Files.Get "configs/default.json") . ) | quote }}
  rules.json: {{ .Values.rules | quote }}
  