{{- $dbHost := (.Values.config.db_host | replace "$release_name" .Release.Name) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "centralsettlement.fullname" . }}
  labels:
      app: {{ template "centralsettlement.fullname" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
data:
  default.json: |
    {{ .Values.config.default_json | replace "$service_api_port" (printf "%.0f" .Values.service.ports.api.internalPort) | replace "$dbdriver" .Values.config.db_type | replace "$dbuser" .Values.config.db_user | replace "$dbpassword" .Values.config.db_password | replace "$dbhost" $dbHost | replace "$dbport" (printf "%.0f" .Values.config.db_port) | replace "$dbname" .Values.config.db_database }}
  
#  knexfile.js: |
#    'use strict'
#
#    const migrationsDirectory = '/opt/central-settlement/migrations'
#    const Config = require('/opt/central-settlement/src/lib/config')
#    module.exports = {
#      client: 'pg',
#      connection: Config.DATABASE_URI,
#      migrations: {
#        directory: migrationsDirectory,
#        tableName: 'migrations',
#        stub: `${migrationsDirectory}/migration.template`
#      }
#    }
