# This is a YAML-formatted file.

global:
  kafka:
    host: kafka
    port: 9092

  redis:
    host: redis
    port: 6379

mojaloop-ttk-sim1-svc:
  enabled: true

  ## Local re-usable configs
  config:
    simName: &CONFIG_SIM1_NAME ml-ttk-sim1
    database: &CONFIG_SIM1_DB 1

  sdk-scheme-adapter:
    sdk-scheme-adapter-api-svc:
      # kafka:
      #   host: kafka
      #   port: 9092

      redis:
        # host: redis
        # port: 6379
        database: *CONFIG_SIM1_DB # This is a number between 0 to 15

      config:
        simName: *CONFIG_SIM1_NAME

      env:
        PEER_ENDPOINT: '{{ .Release.Name }}-ml-ttk-sim2-sdk-api-svc:4000'
        ALS_ENDPOINT: '{{ .Release.Name }}-ml-ttk-sim2-sdk-api-svc:4000'
        QUOTES_ENDPOINT: '{{ .Release.Name }}-ml-ttk-sim2-sdk-api-svc:4000'
        BULK_QUOTES_ENDPOINT: '{{ .Release.Name }}-ml-ttk-sim2-sdk-api-svc:4000'
        TRANSACTION_REQUESTS_ENDPOINT: '{{ .Release.Name }}-ml-ttk-sim2-sdk-api-svc:4000'
        TRANSFERS_ENDPOINT: '{{ .Release.Name }}-ml-ttk-sim2-sdk-api-svc:4000'
        BULK_TRANSFERS_ENDPOINT: '{{ .Release.Name }}-ml-ttk-sim2-sdk-api-svc:4000'

    sdk-scheme-adapter-dom-evt-handler:
      # kafka:
      #   host: kafka
      #   port: 9092

      redis:
        # host: redis
        # port: 6379
        database: *CONFIG_SIM1_DB # This is a number between 0 to 15

      config:
        simName: *CONFIG_SIM1_NAME

    sdk-scheme-adapter-cmd-evt-handler:
      # kafka:
      #   host: kafka
      #   port: 9092

      redis:
        # host: redis
        # port: 6379
        database: *CONFIG_SIM1_DB # This is a number between 0 to 15

      config:
        simName: *CONFIG_SIM1_NAME

  ml-testing-toolkit:
    enabled: true
    ml-testing-toolkit-backend:
      ingress:
        enabled: true
        hosts:
          specApi:
            host: 'ttksim1-specapi.ttk1.test.mojaloop.live'
          adminApi:
            host: 'ttksim1.ttk1.test.mojaloop.live'
    ml-testing-toolkit-frontend:
      ingress:
        enabled: true
        hosts:
          ui:
            host: ttksim1.ttk1.test.mojaloop.live
      config:
        API_BASE_URL: 'http://ttksim1.ttk1.test.mojaloop.live'

mojaloop-ttk-sim2-svc:
  enabled: true

  ## Local re-usable configs
  config:
    simName: &CONFIG_SIM2_NAME ml-ttk-sim2
    database: &CONFIG_SIM2_DB 2

  sdk-scheme-adapter:
    sdk-scheme-adapter-api-svc:
      # kafka:
      #   host: kafka
      #   port: 9092

      redis:
        # host: redis
        # port: 6379
        database: *CONFIG_SIM2_DB # This is a number between 0 to 15

      config:
        simName: *CONFIG_SIM2_NAME

      env:
        PEER_ENDPOINT: '{{ .Release.Name }}-ml-ttk-sim1-sdk-api-svc:4000'
        ALS_ENDPOINT: '{{ .Release.Name }}-ml-ttk-sim1-sdk-api-svc:4000'
        QUOTES_ENDPOINT: '{{ .Release.Name }}-ml-ttk-sim1-sdk-api-svc:4000'
        BULK_QUOTES_ENDPOINT: '{{ .Release.Name }}-ml-ttk-sim1-sdk-api-svc:4000'
        TRANSACTION_REQUESTS_ENDPOINT: '{{ .Release.Name }}-ml-ttk-sim1-sdk-api-svc:4000'
        TRANSFERS_ENDPOINT: '{{ .Release.Name }}-ml-ttk-sim1-sdk-api-svc:4000'
        BULK_TRANSFERS_ENDPOINT: '{{ .Release.Name }}-ml-ttk-sim1-sdk-api-svc:4000'

    sdk-scheme-adapter-dom-evt-handler:
      # kafka:
      #   host: kafka
      #   port: 9092

      redis:
        # host: redis
        # port: 6379
        database: *CONFIG_SIM2_DB # This is a number between 0 to 15

      config:
        simName: *CONFIG_SIM2_NAME

    sdk-scheme-adapter-cmd-evt-handler:
      # kafka:
      #   host: kafka
      #   port: 9092

      redis:
        # host: redis
        # port: 6379
        database: *CONFIG_SIM2_DB # This is a number between 0 to 15

      config:
        simName: *CONFIG_SIM2_NAME

  ml-testing-toolkit:
    enabled: true
    ml-testing-toolkit-backend:
      ingress:
        enabled: true
        hosts:
          specApi:
            host: 'ttksim2-specapi.ttk1.test.mojaloop.live'
          adminApi:
            host: 'ttksim2.ttk1.test.mojaloop.live'
    ml-testing-toolkit-frontend:
      ingress:
        enabled: true
        hosts:
          ui:
            host: 'ttksim2.ttk1.test.mojaloop.live'
      config:
        API_BASE_URL: 'http://ttksim2.ttk1.test.mojaloop.live'

mojaloop-ttk-sim3-svc:
  enabled: true

  ## Local re-usable configs
  config:
    simName: &CONFIG_SIM3_NAME ml-ttk-sim3
    database: &CONFIG_SIM3_DB 3

  sdk-scheme-adapter:
    sdk-scheme-adapter-api-svc:
      # kafka:
      #   host: kafka
      #   port: 9092

      redis:
        # host: redis
        # port: 6379
        database: *CONFIG_SIM3_DB # This is a number between 0 to 15

      config:
        simName: *CONFIG_SIM3_NAME

    sdk-scheme-adapter-dom-evt-handler:
      # kafka:
      #   host: kafka
      #   port: 9092

      redis:
        # host: redis
        # port: 6379
        database: *CONFIG_SIM3_DB # This is a number between 0 to 15

      config:
        simName: *CONFIG_SIM3_NAME

    sdk-scheme-adapter-cmd-evt-handler:
      # kafka:
      #   host: kafka
      #   port: 9092

      redis:
        # host: redis
        # port: 6379
        database: *CONFIG_SIM3_DB # This is a number between 0 to 15

      config:
        simName: *CONFIG_SIM3_NAME

  ml-testing-toolkit:
    enabled: true
    ml-testing-toolkit-backend:
      ingress:
        enabled: true
        hosts:
          specApi:
            host: 'ttksim3-specapi.ttk1.test.mojaloop.live'
          adminApi:
            host: 'ttksim3.ttk1.test.mojaloop.live'
    ml-testing-toolkit-frontend:
      ingress:
        enabled: true
        hosts:
          ui:
            host: 'ttksim3.ttk1.test.mojaloop.live'
      config:
        API_BASE_URL: 'http://ttksim3.ttk1.test.mojaloop.live'
