## Pod scheduling preferences.
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}

## Set toleration for scheduler
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Default values shared by all containers
config:
  db_protocol: 'mysql'
  db_host: mysqldb
  db_port: '3306'
  db_user: 'central_ledger'
  db_password: ml_password
  db_database: 'central_ledger'

## @param master.podLabels Extra labels for pod(s)
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
podLabels: {}

## @param podAnnotations Additional custom annotations for pod(s)
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

service:
  type: ClusterIP

imageCredentials:
  name: pull-secrets

# Default values for operator-settlement
operatorSettlement:
  image:
    repository: mojaloop/operator-settlement
    tag: v11.0.0
    pullPolicy: IfNotPresent

  service:
    port: 80

  init:
    enabled: true
    image:
      repository: mojaloop/operator-settlement
      tag: v11.0.0
      pullPolicy: IfNotPresent
    command: mysql -h $db_host -P $db_port -u $db_user --password=$db_password  $db_database < /opt/operator-settlement/init.sql

  ingress:
    enabled: false
    externalPath: /
    hosts:
      api: operator-settlement.local
    annotations: {}
      # nginx.ingress.kubernetes.io/rewrite-target: /$1
      ## https://kubernetes.github.io/ingress-nginx/examples/rewrite/
      # nginx.ingress.kubernetes.io/rewrite-target: '/'
      # nginx.ingress.kubernetes.io/rewrite-target: '/$2'
      ## https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/
      # kubernetes.io/ingress.class: nginx
      ## https://kubernetes.github.io/ingress-nginx/user-guide/tls/#automated-certificate-management-with-kube-lego
      # kubernetes.io/tls-acme: "true"
    tls: []

# Default values for settlement-management
settlementManagement:
  image:
    repository: mojaloop/settlement-management
    tag: v11.0.0
    pullPolicy: IfNotPresent

  service:
    port: 5000

  init:
    enabled: true
    image:
      repository: mojaloop/settlement-management
      tag: v11.0.0
      pullPolicy: IfNotPresent
    command: mysql -h $db_host -P $db_port -u $db_user --password=$db_password  $db_database < /opt/settlement-management/init.sql

  config:
    CENTRAL_LEDGER_SERVICE_NAME: '$release_name-centralledger-service'
    CENTRAL_LEDGER_SERVICE_ADMIN_PORT: '80'
    SETTLEMENTS_SERVICE_NAME: '$release_name-centralsettlement'
    SETTLEMENTS_SERVICE_PORT: '80'
    MIN_WINDOW_AGE_MS: '5000'
    OPERATOR_SETTLEMENTS_SERVICE_NAME: '$release_name-finance-portal-settlement-management'
    OPERATOR_SETTLEMENTS_SERVICE_PORT: '80'

  ingress:
    enabled: false
    externalPath: /
    hosts:
      api: settlement-management.local
    annotations: {}
      # nginx.ingress.kubernetes.io/rewrite-target: /$1
      ## https://kubernetes.github.io/ingress-nginx/examples/rewrite/
      # nginx.ingress.kubernetes.io/rewrite-target: '/'
      # nginx.ingress.kubernetes.io/rewrite-target: '/$2'
      ## https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/
      # kubernetes.io/ingress.class: nginx
      ## https://kubernetes.github.io/ingress-nginx/user-guide/tls/#automated-certificate-management-with-kube-lego
      # kubernetes.io/tls-acme: "true"
    tls: []
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
