{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "centralledger.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "centralledger.fullname" . }}
  labels:
    app: {{ template "centralledger.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hosts.api }}
      http:
        paths:
          - path: {{ .Values.ingress.externalPath.api }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ .Values.containers.api.service.ports.api.externalPort }}
          - path: {{ .Values.ingress.externalPath.admin }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ .Values.containers.admin.service.ports.api.externalPort }}
  {{- if .Values.ingress.tls }}
  tls:
    {{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}