apiVersion: v1
kind: Service
metadata:
  name: {{ template "centralledger.fullname" . }}
  labels:
    app: {{ template "centralledger.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $port := .Values.containers.api.service.ports }}
    - port: {{ $port.externalPort }}
      targetPort: {{ $port.internalPort }}
      protocol: TCP
      name: {{ $port.name }}
    {{- end }}
    {{- range $port := .Values.containers.admin.service.ports }}
    - port: {{ $port.externalPort }}
      targetPort: {{ $port.internalPort }}
      protocol: TCP
      name: {{ $port.name }}
    {{- end }}
{{- if not .Values.service.external.enabled }}
  selector:
    app: {{ template "centralledger.fullname" . }}
    release: {{ .Release.Name }}
{{- end -}}
