{{- if .Values.enabled -}}
{{- $MYSQL_COMMAND := (.Values.global.mysql.command | replace "$mysql_host" (.Values.global.mysql.host) | replace "$mysql_port" (print .Values.global.mysql.port) | replace "$release_name" (.Release.Name) ) -}}
{{- $KEYCLOAK_COMMAND := (.Values.global.keycloak.command | replace "$keycloak_host" (.Values.global.keycloak.host) | replace "$keycloak_port" (print .Values.global.keycloak.port) | replace "$release_name" (.Release.Name) ) -}}
apiVersion: {{ template "connection-manager-backend.apiVersion.Deployment" . }}
kind: Deployment
metadata:
  name: {{ include "connection-manager-backend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "connection-manager-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "connection-manager-backend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "connection-manager-backend.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      initContainers:
        {{- if .Values.global.mysql.enabled }}
        - name: mysql-checker
          image: "docker.io/busybox:1.32"
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - {{ $MYSQL_COMMAND }}
        {{- end }}
        {{- if .Values.global.keycloak.enabled }}
        - name: keycloak-checker
          image: "docker.io/busybox:1.32"
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - {{ $KEYCLOAK_COMMAND }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.ports.adminApi.internalPort }}
          envFrom:
          - configMapRef:
              name: {{ template "connection-manager-backend.fullname" . }}-config
{{- end -}}