{{- $forensicLoggingSidecarHost := printf "%s-%s" .Release.Name .Values.config.forensicloggingsidecar_host -}}
{{- $kafkaHost := printf "%s-%s" .Release.Name .Values.config.kafka_host }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "centralledger-handler-admin-transfer.fullname" . }}
  labels:
      app: {{ template "centralledger-handler-admin-transfer.fullname" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
data:
  server.host: {{ .Values.ingress.hosts.api | quote }}
  server.port: {{ .Values.containers.api.service.ports.api.internalPort | quote }}
  {{- if not .Values.global.config.externalKafka }}
  default.json: {{ (.Values.config.default_json | replace "$service_api_port" (printf "%.0f" .Values.containers.api.service.ports.api.internalPort) | replace "$ingress_host" .Values.ingress.hosts.api | replace "$forensicloggingsidecar_host" $forensicLoggingSidecarHost | replace "$forensicloggingsidecar_port" (printf "%.0f" .Values.config.forensicloggingsidecar_port) | replace "$kafka_host" (default .Values.config.kafka_host $kafkaHost) | replace "$kafka_port" (printf "%.0f" .Values.config.kafka_port) ) | quote }}
  {{- else }}
  default.json: {{ (.Values.config.default_json | replace "$service_api_port" (printf "%.0f" .Values.containers.api.service.ports.api.internalPort) | replace "$ingress_host" .Values.ingress.hosts.api | replace "$forensicloggingsidecar_host" $forensicLoggingSidecarHost | replace "$forensicloggingsidecar_port" (printf "%.0f" .Values.config.forensicloggingsidecar_port) | replace "$kafka_host" .Values.config.kafka_host | replace "$kafka_port" (printf "%.0f" .Values.config.kafka_port) ) | quote }}
  {{- end }}
  knexfile.js: {{ (.Values.config.knexfile_js | replace "$db_driver" .Values.config.db_driver) | quote}}
