mojaloop-bulk:
  enabled: true
mojaloop-ttk-simulators:
  enabled: true
  mojaloop-ttk-sim1-svc:
    enabled: true
    sdk-scheme-adapter:
      sdk-scheme-adapter-api-svc:
        livenessProbe: false
        readinessProbe: false
      sdk-scheme-adapter-dom-evt-handler:
        livenessProbe: false
        readinessProbe: false
      sdk-scheme-adapter-cmd-evt-handler:
        livenessProbe: false
        readinessProbe: false
  mojaloop-ttk-sim2-svc:
    enabled: true
    sdk-scheme-adapter:
      sdk-scheme-adapter-api-svc:
        livenessProbe: false
        readinessProbe: false
      sdk-scheme-adapter-dom-evt-handler:
        livenessProbe: false
        readinessProbe: false
      sdk-scheme-adapter-cmd-evt-handler:
        livenessProbe: false
        readinessProbe: false
  mojaloop-ttk-sim3-svc:
    enabled: true
    sdk-scheme-adapter:
      sdk-scheme-adapter-api-svc:
        livenessProbe: false
        readinessProbe: false
      sdk-scheme-adapter-dom-evt-handler:
        livenessProbe: false
        readinessProbe: false
      sdk-scheme-adapter-cmd-evt-handler:
        livenessProbe: false
        readinessProbe: false