cl-mongodb:
  enabled: false
ttk-mongodb:
  enabled: false
ttksims-redis:
  enabled: false
auth-svc-redis:
  enabled: false
proxy-cache-redis:
  enabled: true
proxy-cache-redis-standalone:
  enabled: false