config:
  rules:
    - ruleId: R999
      priority: 999
      description: Catch-all for specific DFSP code subId
      match:
        type: MSISDN
        id:
          mode: ANY
        subId:
          mode: EXACT
          value: DFSP_CODE
      result:
        dfspId: dfsp1
    - ruleId: R010
      priority: 10
      description: Prefix match for India (91)
      match:
        type: MSISDN
        id:
          mode: PREFIX
          value: "91"
      result:
        dfspId: ttkpayeefsp