{{- if .Values.ingress.enabled -}}
{{- $k8sVer := .Capabilities.KubeVersion.Version -}}
{{- if semverCompare ">=1.19-0" $k8sVer -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "connection-manager.fullname" . }}-ingress
{{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if semverCompare ">=1.19-0" $k8sVer }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api/
            {{- if semverCompare ">=1.19-0" $k8sVer }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend:
            {{- if semverCompare ">=1.19-0" $k8sVer }}
              service:
                name: {{ include "connection-manager.fullname" . }}-api
                port:
                  number: {{ .Values.api.ports.containerPort }}
            {{- else }}
              serviceName: {{ include "connection-manager.fullname" . }}-api
              servicePort: {{ .Values.api.ports.containerPort }}
            {{- end }}
          - path: /
            {{- if semverCompare ">=1.19-0" $k8sVer }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend:
            {{- if semverCompare ">=1.19-0" $k8sVer }}
              service:
                name: {{ include "connection-manager.fullname" . }}-ui
                port:
                  number: {{ .Values.ui.ports.containerPort }}
            {{- else }}
              serviceName: {{ include "connection-manager.fullname" . }}-ui
              servicePort: {{ .Values.ui.ports.containerPort }}
            {{- end }}
{{- end -}}
