apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ml-api-adapter-handler-notification.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "ml-api-adapter-handler-notification.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  default.json: {{ (tpl (.Files.Get "configs/default.json") . ) | quote }}

{{- if .Values.sidecar.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ml-api-adapter-handler-notification.fullname" . }}-sidecar
  labels:
    app.kubernetes.io/name: {{ include "ml-api-adapter-handler-notification.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  default.json: {{ (tpl (.Files.Get "configs/default-sidecar.json") . ) | quote }}
{{- end }}
