apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mockpathfinder.fullname" . }}
  labels:
    app: {{ template "mockpathfinder.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  default.json: |
    {{ .Values.config.default_json | replace "$query_port" (printf "%.0f" .Values.service.ports.query.internalPort) | replace "$provisioning_port" (printf "%.0f" .Values.service.ports.provisioning.internalPort) }}
  knexfile.js: |
    'use strict'

    const migrationsDirectory = '/opt/mock-pathfinder/migrations'
    const Config = require('/opt/mock-pathfinder/src/lib/config')

    module.exports = {
      client: 'pg',
      connection: Config.DATABASE_URI,
      migrations: {
        directory: migrationsDirectory,
        tableName: 'migrations',
        stub: `${migrationsDirectory}/migration.template`
      }
    }
