{{- range $name, $customConfig := .Values.simulators }}
{{- $config := merge $customConfig $.Values.defaults }}
{{- $fullName := printf "%s%s" (include "mojaloop-simulator.prefix" $) $name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-rules
  labels:
    app.kubernetes.io/name: sim-{{ $name }}-rules
    {{- include "mojaloop-simulator.common-labels" $ | nindent 4 }}
data:
  rules.json: {{ $config.config.backend.rules | quote }}
---
{{- end }}
