apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "centralledger-handler-bulk-transfer-prepare.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "centralledger-handler-bulk-transfer-prepare.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  default.json: {{ (tpl (.Files.Get "configs/default.json") . ) | quote }}
  knexfile.js: {{ (tpl (.Files.Get "configs/knexfile.js") . ) | quote }}