{{- $dbHost := ( .Values.config.db_host | replace "$release_name" .Release.Name ) -}}
{{- $kafkaHost := ( .Values.config.kafka_host | replace "$release_name" .Release.Name ) -}}
{{- $objStoreUri := ( .Values.config.objstore_uri | replace "$release_name" .Release.Name ) -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "centralledger-handler-bulk-transfer-prepare.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "centralledger-handler-bulk-transfer-prepare.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "centralledger-handler-bulk-transfer-prepare.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "centralledger-handler-bulk-transfer-prepare.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/port: "{{ .Values.containers.api.service.ports.api.internalPort }}"
        prometheus.io/scrape: "true"
      {{- end }}
    spec:
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
      {{- if .Values.init.enabled }}
      initContainers:
        - name: {{ .Values.init.mongodb.name }}
          image: {{ .Values.init.mongodb.repository }}:{{ .Values.init.mongodb.tag }}
          imagePullPolicy: {{ .Values.init.mongodb.pullPolicy }}
          command:
            - sh
            - "-c"
            - {{ (.Values.init.mongodb.command | replace "$mongouri" $objStoreUri) | quote }}
        {{- if eq .Values.config.db_type "postgres"}}
        - name: {{ .Values.init.psql.name }}
          image: {{ .Values.init.psql.repository }}:{{ .Values.init.psql.tag }}
          imagePullPolicy: {{ .Values.init.psql.pullPolicy }}
          env:
          - name: "POSTGRES_URL"
            value: "postgresql://{{ .Values.config.db_user }}:{{ .Values.config.db_password }}@{{ $dbHost }}:{{ .Values.config.db_port }}/{{ .Values.config.db_database }}?sslmode=disable"
        {{- end }}
        {{- if eq .Values.config.db_type "mysql"}}
        - name: {{ .Values.init.mysql.name }}
          image: {{ .Values.init.mysql.repository }}:{{ .Values.init.mysql.tag }}
          imagePullPolicy: {{ .Values.init.mysql.pullPolicy }}
          command:
            - sh
            - "-c"
            - {{ (.Values.init.mysql.command | replace "$db_user" (print .Values.config.db_user) | replace "$db_password" (print .Values.config.db_password) | replace "$db_host" $dbHost | replace "$db_database" (print .Values.config.db_database) | replace "$db_port" (print .Values.config.db_port) )| quote }}
        {{- end }}
        - name: {{ .Values.init.kafka.name }}
          image: {{ .Values.init.kafka.repository }}:{{ .Values.init.kafka.tag }}
          imagePullPolicy: {{ .Values.init.kafka.pullPolicy }}
          command:
            - sh
            - "-c"
            - {{ (.Values.init.kafka.command | replace "$kafka_host" $kafkaHost | replace "$kafka_port" (printf "%.0f" .Values.config.kafka_port) ) | quote }}
          env:
          {{- range $envItem := .Values.init.kafka.env }}
            - name: {{ $envItem.name }}
              value: {{ $envItem.value }}
          {{- end }}
      {{- end }}
      containers:
        - name: {{ template "centralledger-handler-bulk-transfer-prepare.name" . }}
          image: "{{ .Values.containers.api.image.repository }}:{{ .Values.containers.api.image.tag }}"
          imagePullPolicy: {{ .Values.containers.api.image.pullPolicy }}
          command: {{ .Values.containers.api.image.command }}
          ports:
          {{- range $port := .Values.containers.api.service.ports }}
            - name: {{ $port.name }}
              containerPort: {{ $port.internalPort }}
          {{- end }}
          {{- if .Values.containers.api.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.containers.api.readinessProbe.httpGet.path }}
              port: {{ .Values.containers.api.service.ports.api.internalPort }}
            initialDelaySeconds: {{ .Values.containers.api.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.containers.api.readinessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.containers.api.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.containers.api.livenessProbe.httpGet.path }}
              port: {{ .Values.containers.api.service.ports.api.internalPort }}
            initialDelaySeconds: {{ .Values.containers.api.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.containers.api.livenessProbe.periodSeconds }}
          {{- end }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.config.log_level }}
            - name: CSL_LOG_TRANSPORT
              value: {{ .Values.config.log_transport}}
          volumeMounts:
          - name: {{ template "centralledger-handler-bulk-transfer-prepare.fullname" . }}-config-volume
            mountPath: /opt/central-ledger/config
      volumes:
        - name: {{ template "centralledger-handler-bulk-transfer-prepare.fullname" . }}-config-volume
          configMap:
            name: {{ template "centralledger-handler-bulk-transfer-prepare.fullname" . }}-config
            items:
            - key: default.json
              path: default.json
            - key: knexfile.js
              path: knexfile.js
